"""Document checklists shown on the Resources page and offered as PDFs.

To add or change a checklist: edit this file, then run  python tools/build.py
Each checklist: slug (used in the link and the PDF name), tag, title, optional note, items.
"""

GROUPS = [
    {'id': 'company', 'title': 'Company and firm registration', 'lists': [
        {'slug': 'private-limited-company-incorporation', 'tag': 'New ventures', 'title': 'Private Limited company incorporation',
         'note': 'At least two directors, one of whom lives in India, and at least two shareholders.',
         'items': [
             'PAN of every director and shareholder',
             'Aadhaar of Indian directors, or a passport for foreign directors',
             'A recent passport-size photograph of each director',
             'Address proof of each director: a bank statement or utility bill not older than two months',
             'Mobile number and email address of each director',
             'Two or three proposed company names, in order of preference',
             'The main business objects of the company',
             'Authorised capital, paid-up capital and each shareholder’s share',
             'Registered office proof: rent agreement or ownership proof, the owner’s consent letter and a utility bill not older than two months',
             'Digital Signature Certificate (DSC) for each director; we can arrange these',
         ]},
        {'slug': 'llp-incorporation', 'tag': 'New ventures', 'title': 'LLP incorporation',
         'note': 'At least two designated partners, one of whom lives in India.',
         'items': [
             'PAN of every partner',
             'Aadhaar of Indian partners, or a passport for foreign partners',
             'A recent passport-size photograph of each partner',
             'Address proof of each partner: a bank statement or utility bill not older than two months',
             'Mobile number and email address of each partner',
             'Two or three proposed LLP names, in order of preference',
             'The main business of the LLP',
             'Capital contribution and profit-sharing ratio of each partner',
             'Registered office proof: rent agreement or ownership proof, the owner’s consent letter and a utility bill not older than two months',
             'Digital Signature Certificate (DSC) for each designated partner; we can arrange these',
         ]},
        {'slug': 'company-annual-filings', 'tag': 'Companies', 'title': 'Annual filings for a company (ROC)',
         'items': [
             'Trial balance and financial statements for the year',
             'Bank statements and loan statements for the year',
             'List of directors and their DIN',
             'List of shareholders and their shareholding',
             'Minutes of board and general meetings held during the year',
             'Auditor’s details and appointment letter',
             'Details of any change in directors, capital or registered office',
             'Digital Signature Certificates (DSC) of the directors who will sign',
             'Previous year’s filings, for reference',
         ]},
        {'slug': 'partnership-firm-formation', 'tag': 'New ventures', 'title': 'Forming a partnership firm',
         'note': 'At least two partners. We draft the deed, and register the firm with the Registrar of Firms if you want it registered.',
         'items': [
             'PAN and Aadhaar of every partner',
             'A recent passport-size photograph of each partner',
             'Address proof of each partner',
             'Two or three proposed firm names, in order of preference',
             'Capital each partner will put in, and the profit-sharing ratio',
             'The main business of the firm',
             'Proof of the business address: rent agreement or ownership proof, the owner’s consent letter and a utility bill',
             'Mobile number and email address of each partner',
             'Stamp paper for the deed, which we can arrange',
         ]},
    ]},
    {'id': 'income-tax', 'title': 'Income tax', 'lists': [
        {'slug': 'income-tax-return', 'tag': 'Individuals', 'title': 'Filing your income tax return',
         'items': [
             'PAN, and Aadhaar linked to it',
             'Form 16 or salary slips for the year',
             'Form 26AS and Annual Information Statement (AIS)',
             'Bank statements and interest certificates',
             'Rent receipts, if you claim house rent allowance',
             'Home loan interest certificate, if you have a home loan',
             'Investment and insurance proofs, such as PPF, ELSS, life insurance and tuition fees',
             'Details of capital gains, such as shares, mutual funds or property sales',
             'Details of any other income, such as rent, interest or freelance receipts',
             'Last year’s return, and details of any foreign assets',
         ]},
        {'slug': 'business-income-tax-return', 'tag': 'Businesses', 'title': 'Income tax return for a business or profession',
         'note': 'For proprietors, professionals and firms. Companies and LLPs also need their audited accounts.',
         'items': [
             'PAN and Aadhaar of the proprietor, or PAN of the firm',
             'Sales and purchase records, or the books of accounts for the year',
             'Bank statements for every business account',
             'GST returns for the year, if registered',
             'TDS certificates, Form 26AS and the AIS',
             'Profit and loss account and balance sheet, if already prepared',
             'Fixed asset details and purchase bills for new assets',
             'Loan statements and interest certificates',
             'Advance tax and self-assessment tax challans',
             'Previous year’s return and computation',
             'Tax audit report, if an audit applies to you',
         ]},
        {'slug': 'tan-tds-registration', 'tag': 'Employers and payers', 'title': 'TAN registration for TDS',
         'items': [
             'PAN of the business, company or proprietor',
             'Name and status of the deductor: individual, firm, company, trust or other',
             'Address of the business, with a PIN code',
             'Name, designation and PAN of the person responsible for deducting tax',
             'Mobile number and email address of the business',
             'Certificate of incorporation or partnership deed, for firms and companies',
             'Aadhaar of the proprietor or authorised signatory',
         ]},
    ]},
    {'id': 'gst', 'title': 'GST', 'lists': [
        {'slug': 'proprietorship-gst-registration', 'tag': 'Businesses', 'title': 'GST registration for a proprietorship',
         'items': [
             'PAN of the proprietor, and Aadhaar',
             'A recent passport-size photograph of the proprietor',
             'Mobile number and email address, which will receive the OTPs',
             'Proof of the business address: for your own premises, a latest electricity bill or property tax receipt',
             'For rented premises: the rent agreement, the owner’s consent letter and the owner’s latest electricity bill',
             'Bank account proof: a cancelled cheque, or the first page of the passbook or a statement',
             'The goods or services you deal in, with their HSN or SAC codes if you have them',
             'Shop licence, trade licence or Udyam certificate, if you have one',
         ]},
        {'slug': 'partnership-gst-registration', 'tag': 'Firms', 'title': 'GST registration for a partnership firm',
         'items': [
             'Partnership deed (and the registration certificate, if the firm is registered)',
             'PAN of the firm',
             'PAN, Aadhaar and passport-size photographs of all partners',
             'Letter authorising one partner to sign and file, with that person’s photograph',
             'Mobile number and email address of the authorised signatory, for the OTPs',
             'Proof of the principal place of business: electricity bill or property tax receipt for your own premises',
             'For rented premises: the rent agreement, the owner’s consent letter and the owner’s latest electricity bill',
             'Bank account proof in the name of the firm: a cancelled cheque or statement',
             'The goods or services you deal in, with their HSN or SAC codes if you have them',
         ]},
        {'slug': 'company-llp-gst-registration', 'tag': 'Companies and LLPs', 'title': 'GST registration for a company or LLP',
         'items': [
             'Certificate of incorporation and PAN of the company or LLP',
             'MOA and AOA for a company, or the LLP agreement for an LLP',
             'PAN, Aadhaar and photographs of the directors or designated partners',
             'Board resolution or authorisation letter naming the authorised signatory',
             'Digital Signature Certificate (DSC) of the authorised signatory',
             'Proof of the registered office, as for rented or own premises',
             'Bank account proof in the name of the company or LLP',
             'Mobile number and email address of the authorised signatory',
             'The goods or services you deal in, with their HSN or SAC codes if you have them',
         ]},
        {'slug': 'gst-return-filing', 'tag': 'Registered businesses', 'title': 'Monthly GST return filing',
         'items': [
             'Sales invoices for the month, including exports and nil-rated sales',
             'Purchase invoices and expense bills with the supplier’s GSTIN',
             'Credit notes and debit notes issued and received',
             'Bank statements for the month',
             'GSTR-2B for the month, to match your input tax credit',
             'E-way bill details, if you move goods',
             'Previous month’s return and the tax paid, for reference',
             'GST portal login, if you have changed it',
         ]},
    ]},
    {'id': 'licences', 'title': 'Registrations and licences', 'lists': [
        {'slug': 'msme-udyam-registration', 'tag': 'Businesses', 'title': 'MSME (Udyam) registration',
         'items': [
             'Aadhaar of the proprietor, a partner, or the authorised signatory, with the mobile number linked to it',
             'PAN of the business',
             'GSTIN, if the business is registered under GST',
             'Name, type and address of the enterprise',
             'Date the business started',
             'Main activity of the business, so we can choose the right code',
             'Number of people employed',
             'Bank account number and IFSC code',
             'Investment in machinery or equipment, and turnover figures',
         ]},
        {'slug': 'esi-pf-registration', 'tag': 'Employers', 'title': 'ESI and PF registration',
         'items': [
             'PAN of the business',
             'Certificate of incorporation, partnership deed, or shop licence or GST certificate',
             'Address proof of the establishment',
             'Cancelled cheque or bank statement of the business account',
             'List of employees with Aadhaar, date of birth, date of joining and monthly wages',
             'Existing UAN or ESI number of each employee, if they have one',
             'PAN and Aadhaar of the employer or authorised signatory',
             'Digital Signature Certificate (DSC) of the employer or authorised signatory',
             'Mobile number and email address of the employer',
         ]},
        {'slug': 'import-export-code', 'tag': 'Traders', 'title': 'Import Export Code (IEC) registration',
         'items': [
             'PAN of the proprietor, firm or company',
             'Aadhaar of the proprietor or authorised signatory',
             'Certificate of incorporation or partnership deed, for firms and companies',
             'Address proof of the business premises',
             'Cancelled cheque with the name printed on it, or a bank certificate',
             'Mobile number and email address, for the OTPs',
             'Digital Signature Certificate (DSC), for firms and companies',
             'A passport-size photograph of the applicant',
         ]},
        {'slug': 'fssai-licence', 'tag': 'Food businesses', 'title': 'FSSAI food licence',
         'note': 'The exact list depends on whether you need a basic registration, a state licence or a central licence.',
         'items': [
             'Photo ID and passport-size photograph of the proprietor, partners or directors',
             'Proof of the business address',
             'Proof of the right to use the premises: rent agreement and consent letter, or ownership proof',
             'List of the food products you will make, store or sell',
             'Layout or floor plan of the premises, for a licence',
             'Partnership deed, or certificate of incorporation with MOA and AOA, for firms and companies',
             'Form IX, nominating the person responsible, for a company',
             'Local body (panchayat or municipality) licence or no-objection letter, where required',
             'Water test report from a recognised laboratory, for manufacturing or processing',
         ]},
        {'slug': 'trade-licence', 'tag': 'Shops and businesses', 'title': 'Trade licence from the local body',
         'note': 'Municipality or panchayat licence. The requirements differ by local body and by type of business.',
         'items': [
             'Application form for the licence',
             'PAN and Aadhaar of the proprietor, or of the partners or directors',
             'Passport-size photographs',
             'Proof of the building: ownership document and latest building tax receipt',
             'For rented premises: the rent agreement and the owner’s consent letter',
             'Layout or plan of the premises, where asked for',
             'Details of the business and the activities carried out',
             'Partnership deed or certificate of incorporation, for firms and companies',
             'Any other licence or no-objection letter the business needs, for example fire or pollution control',
         ]},
        {'slug': 'digital-signature-certificate', 'tag': 'Individuals and businesses', 'title': 'Digital Signature Certificate (DSC)',
         'items': [
             'PAN of the applicant',
             'Aadhaar, with the mobile number linked to it',
             'A recent passport-size photograph',
             'Email address and mobile number of the applicant',
             'For a certificate in a company’s name: certificate of incorporation, and a letter authorising the applicant',
             'For a certificate used for GST or MCA filing: the PAN of the company, firm or LLP',
         ]},
    ]},
    {'id': 'trusts', 'title': 'Trusts and societies', 'lists': [
        {'slug': 'trust-12a-80g-registration', 'tag': 'Trusts', 'title': 'Trust registration for 12A and 80G',
         'note': 'These registrations let a trust claim tax exemption and give its donors a deduction.',
         'items': [
             'Registered trust deed',
             'PAN of the trust',
             'Registration certificate of the trust',
             'PAN, Aadhaar, photographs and address proof of each trustee',
             'Proof of the trust’s office address',
             'Bank account proof in the name of the trust',
             'Details of the activities carried out, with supporting documents',
             'Accounts or income and expenditure statements for the last three years, if the trust is not new',
             'List of donors and donations received, where available',
         ]},
        {'slug': 'society-registration', 'tag': 'Societies', 'title': 'Registering a society',
         'note': 'For Kerala, under the Travancore-Cochin Literary, Scientific and Charitable Societies Registration Act, 1955.',
         'items': [
             'Memorandum of association, with the name and objects of the society',
             'Rules and regulations',
             'List of the governing body or managing committee, with their addresses',
             'PAN, Aadhaar and photographs of the office bearers',
             'Proof of the society’s office address: rent agreement or ownership proof, with the owner’s consent letter',
             'Affidavit and consent letters from the founding members, in the format asked for',
             'Name of the society, with a second choice',
         ]},
    ]},
    {'id': 'notices', 'title': 'Notices', 'lists': [
        {'slug': 'tax-notice-reply', 'tag': 'Notices', 'title': 'Replying to an income tax or GST notice',
         'note': 'Send us the notice as soon as it arrives. The reply date is printed on it.',
         'items': [
             'A complete copy of the notice, with its reference number and reply date',
             'PAN or GSTIN of the person or business the notice is addressed to',
             'The return, assessment order or filing the notice relates to',
             'Form 26AS and AIS, or GSTR-2B and the other GST statements the notice refers to',
             'Bank statements for the period concerned',
             'Invoices, ledgers and workings for the item being questioned',
             'Replies or letters already sent on the same matter',
             'Portal login details, if you want us to view the notice online',
         ]},
    ]},
    {'id': 'loans', 'title': 'Loans', 'lists': [
        {'slug': 'bank-loan-proposal', 'tag': 'Borrowers', 'title': 'Preparing a bank loan proposal',
         'items': [
             'KYC of the promoters',
             'Financial statements and returns for the last two or three years',
             'GST returns for the last 12 months',
             'Bank statements for the last 12 months',
             'Project details, quotations and cost estimates, for a new venture or expansion',
             'Statements of existing loans and repayment schedules',
             'Proof of the promoters’ own contribution',
             'Collateral documents, and registrations such as Udyam',
             'CMA data and projections (we prepare these)',
         ]},
    ]},
]

ALL = [c for g in GROUPS for c in g['lists']]
